project_id = "oeztpxyprifabkvysroh"

[functions.hunter]
verify_jwt = false

[functions.webhook]
verify_jwt = false

[functions.follow-up]
verify_jwt = false

[functions.send-report]
verify_jwt = false

[functions.whatsapp-connect]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false
